version: '3.4'

services:
  productapi:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: ProductApi\Dockerfile

  orderapi:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: OrderApi\Dockerfile


  emailapi:
    image: ${DOCKER_REGISTRY-}emailapi
    build:
      context: .
      dockerfile: EmailApi\Dockerfile


  customerapi:
    image: ${DOCKER_REGISTRY-}customerapi
    build:
      context: .
      dockerfile: CustomerApi\Dockerfile

